Выполняет 3 из 4х задач раздела @vue/cli
js-tasks-ru/vue-20230120_a-vafin85 pull request #5
Opened 2023-02-09 17:32 UTC by VafinArtem

2023-02-09 17:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-12 12:40 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-12 15:34 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-12 19:45 UTC, ShGKme requested changes
В `04-vue-cli/02-TheToaster` требуется либо определять стили тоста внутри компонента тоста, исходя из его типа, либо вынести всю относящуюся к типам стилизацию из компонента тоста. А также использовать события вместо пропса-коллбека.

В `04-vue-cli/03-UiDropdown1` - требуется сделать тип также вычисляемым свойством.

Остальные задачи приняты.

2023-02-12 19:45 UTC, ShGKme commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +  }]">
Статические классы, которые всегда есть у элемента, можно описывать явно в шаблоне через обычный атрибут `class="class-name"`. Так будет видно и основные классы верстки, и какие классы определяются динамически.

2023-02-12 19:45 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      }]"
Все эти классы не описаны в текущем компоненте `TheToaster`, а являются частью `UiToast`. Они работают из-за протекания стилей в `style scope`, а для их использования приходится знать внутренности `UiToast` при его использовании. Эти классы - не часть интерфейса (или как минимум неудобный интерфейс). Вместо этого лучше явно передавать тип, и уже внутри компонента работать с его стилями. И аналогично делать с иконками.

Либо считать, что у `UiToast` никаких типов своих нет, но тогда и стили для разных типов должен определять пользователь, а не разработчик компонента.

2023-02-12 19:45 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
Методы получились почти дублированием. В этом случае хочется иметь какой-то общий базовый метод.

2023-02-12 19:45 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +});
События с именем `update:X` обычно используют только как события для директивы двустороннего связывания `v-model`, чтобы передавать новое значение для свойства, которое передают во входной параметр. В этом компоненте нет параметра `close`, а событие `update:close` не порождается.

2023-02-12 19:45 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  },
`closeToast` - это параметр коллбек. Во Vue принято для передачи данных, которые управляют работой компонента, использовать входные параметры, а для уведомления о чём-то родителя - использовать события. Вместо параметра `closeToast` должно быть событие. `closeToast` - не данные компонента, не управляет его работой. Передача коллбеков в через события:
- удобнее синтаксически за счёт v-on
- явно разделяет разные интерфейсы компонента
- удобнее в отладке, видно в девтулсах

2023-02-12 19:45 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +    <span>{{ message.text }}</span>
С коллбеком незачем отдавать `id`, который этому компоненту в целом не нужен. Его родитель итак знает, у какого тоста срабатывает коллбек `closeToast`. Он знает этот `id`, который сейчас получается вместе с коллбеком, потому что он сам же ему его отдаёт. Сейчас `id` просто получается от родителя и отправляется ему же обратно.

2023-02-12 19:45 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +    <span>{{ message.text }}</span>
`id` - на самом деле не параметр коллбека. Не может быть ситуации, при которой закрытие тоста с ID=1 должно закрывать тост с ID=2

2023-02-12 19:45 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      :close-toast="closeToast"
Здесь `TheToaster` передаёт в `UiToast` айдишник через `:message="message"`, а потом его же ловит и использует в `:close-toast="closeToast"`. Вместо отправки ID по кругу можно явно передать его сразу: `:close-toast="() => closeToast(message.id)"`. В синтаксисе события это будет короче: `@close="closeToast(message.id)"`

2023-02-12 19:45 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    }
Выражение `type.withIcon && type.withoutIcon || type.withIcon` эквивалентно `type.withIcon`.
```
A & B | A === A & (true & B | true) === A & (B | true) === A & true === A
```

2023-02-12 19:45 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    }
В целом вычисление получилось переусложнённое, проверяющее сразу две вещи:
1. есть ли пункты без иконок
2. есть ли пункты с иконками

Что в итоге даёт 4 варианта результата.

А нужно знать только о наличии иконок вообще (2 варианта - есть или нет).

Так метод упрощается до
```js
this.options.some((option) => option.icon)
```

2023-02-12 19:45 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
`type` - не самостоятельные данные компонента. У него нет собственного независимого значения. Также, как `selectedOption` - это результат вычисления от `this.options`. Вместо описания его в `data` и ручного обновления, лучше явно описать его, как вычисляемое свойство.

2023-02-12 19:45 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
Хук `beforeUpdate` используется, когда требуется отреагировать на ререндеринг компонента. Когда реакция требуется именно на обновления DOM или другие изменения, которые не ловятся по изменению данных: обновление DOM в слоте, обновления вне контроля Vue. Такое нужно очень редко.

С таким решением `type` перевычисляется каждый раз, когда ререндерится компонент, даже если на сам `type` это никак повлиять не могло (например, обновление `modelValue`). В других ситуациях это наоборот может не поймать необходимость обновляться, если бы само обновление `type` должно было бы быть причиной для ререндеринга компонента. (Например, если бы `type` вычислялся от данных, которые меняются внутри компонента, но в самом рендеринге больше никак не участвуют).

2023-02-12 19:45 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +  DateType,
Только `MonthType` нужен в свойства экземпляра для использования в шаблоне. Остальные - обычные константы, которые можно использовать напрямую, не добавляя в опции компонента.

2023-02-12 19:45 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +    },
Здесь решение получилось не очень оптимальное. Для каждой ячейки календаря перебираются ВСЕ митапы снова и снова для поиска митапов именной этой ячейки. Включая митапы других месяцев и уже попавших в другие ячейки. Мы точно знаем, что каждый митап попадает только в одну ячейку, и можно не перебирать все митапы каждый раз для каждой клетки каждого месяца. Лучше здесь вычислить какую-то структуру, которая позволяет быстро получить данные для конкретной даты.

2023-02-13 18:06 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-13 18:09 UTC, VafinArtem commented
> В `04-vue-cli/02-TheToaster` требуется либо определять стили тоста внутри компонента тоста, исходя из его типа, либо вынести всю относящуюся к типам стилизацию из компонента тоста. А также использовать события вместо пропса-коллбека.
> 
> В `04-vue-cli/03-UiDropdown1` - требуется сделать тип также вычисляемым свойством.
> 
> Остальные задачи приняты.

Спасибо за такое развернутое ревью. Больше стало понятно особенно с событиями.
За .some() отдельное спасибо, я совсем забыл про этот метод перебора.

2023-02-14 19:19 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-02-14 19:20 UTC, merged